// frames/angular-crax-frame/src/app/table/table.component.ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { ProductService, product } from 'src/services/product-service';

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
})
export class TableComponent {
  products$: Observable<product[]> = new Observable<product[]>();

  constructor(private productService: ProductService) {}

  ngOnInit(): void {
    this.products$ = this.productService.getAll();
  }
}

<table>
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">title</th>
      <th scope="col">price</th>
      <th scope="col">category</th>
      <th scope="col">description</th>
      <th scope="col">image</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let product of products$ | async">
      <td>{{ product.id }}</td>
      <td>{{ product.title }}</td>
      <td>{{ product.price }}</td>
      <td>{{ product.category }}</td>
      <td>{{ product.description }}</td>
      <td><img [src]="product.image" style="width: 8vw" /></td>
    </tr>
  </tbody>
</table>

// apps/request-app/src/components/Table.tsx
import { useEffect } from 'react';
import { product } from 'types/frame/apiTypes';
import { useProductStore } from 'frame/useProductStore';

export function Table() {
	const { products } = useProductStore();
	useEffect(() => {
		console.log(products);
	}, [products]);
	return (
		<table>
			<tr>
				<th scope='col'>id</th>
				<th scope='col'>title</th>
				<th scope='col'>price</th>
				<th scope='col'>category</th>
				<th scope='col'>description</th>
				<th scope='col'>image</th>
			</tr>
			{products.map((product: product) => {
				return (
					<tr>
						<td scope='row'>{product.id}</td>
						<td scope='row'>{product.title}</td>
						<td scope='row'>{product.price}</td>
						<td scope='row'>{product.category}</td>
						<td scope='row'>{product.description}</td>
						<td scope='row'>
							<img src={product.image} style={{ width: '8vw' }} />
						</td>
					</tr>
				);
			})}
		</table>
	);
}
